name: CI & Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
      - 'blink_kernel_freertos_s3-v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      mode:
        description: '运行模式'
        required: false
        type: choice
        options:
          - ci
          - release
      ref:
        description: '代码分支或标签引用'
        required: false
        type: string

jobs:
  CI:
    if: github.event_name != 'push' || github.ref_type != 'tag'
    uses: ./.github/workflows/release_template.yaml
    with:
      ref: ${{ inputs.ref || github.ref }}
      enable_code_analysis: true
      enable_unit_test: true
      enable_build: false
      enable_release: false

  Release:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    uses: ./.github/workflows/release_template.yaml
    with:
      ref: ${{ github.ref_name }}
      enable_code_analysis: false
      enable_unit_test: false
      enable_build: true
      enable_release: true